const requestData = {
  parent_id: "0",
  project_id: "7edc6a9c-8466-499d-af45-f8a7479903f6",
  target_id: "a986199e-ba10-4d0d-ae55-c8cfcb7fc547",
  target_type: "api",
  name: "新建接口222",
  sort: 2,
  version: 1,
  mark: "developing",
  update_day: 1669910400000,
  update_dtime: 1669993207,
  create_dtime: 1669992937,
  status: 1,
  modifier_id: "-1",
  method: "POST",
  mock: "{}",
  mock_url: "/get.php",
  url: "echo.apipost.cn/get.php",
  request: {
    url: "echo.apipost.cn/get.php",
    description: "",
    auth: {
      type: "noauth",
      kv: {
        key: "",
        value: "",
      },
      bearer: {
        key: "",
      },
      basic: {
        username: "",
        password: "",
      },
      digest: {
        username: "",
        password: "",
        realm: "",
        nonce: "",
        algorithm: "",
        qop: "",
        nc: "",
        cnonce: "",
        opaque: "",
      },
      hawk: {
        authId: "",
        authKey: "",
        algorithm: "",
        user: "",
        nonce: "",
        extraData: "",
        app: "",
        delegation: "",
        timestamp: "",
        includePayloadHash: -1,
      },
      awsv4: {
        accessKey: "",
        secretKey: "",
        region: "",
        service: "",
        sessionToken: "",
        addAuthDataToQuery: -1,
      },
      ntlm: {
        username: "",
        password: "",
        domain: "",
        workstation: "",
        disableRetryRequest: 1,
      },
      edgegrid: {
        accessToken: "",
        clientToken: "",
        clientSecret: "",
        nonce: "",
        timestamp: "",
        baseURi: "",
        headersToSign: "",
      },
      oauth1: {
        consumerKey: "",
        consumerSecret: "",
        signatureMethod: "",
        addEmptyParamsToSign: -1,
        includeBodyHash: -1,
        addParamsToHeader: -1,
        realm: "",
        version: "1.0",
        nonce: "",
        timestamp: "",
        verifier: "",
        callback: "",
        tokenSecret: "",
        token: "",
      },
    },
    body: {
      mode: "json",
      parameter: [],
      raw: '{"revenueTp":"01","isIndividualMchnt":"0","insNameCn":"滴沥（广州）信息科技有限公司","settleTp":"01","interBankNo":"104581008078","outAcntNm":"中国银行股份有限公司广州市绿色金融改革创新试验区花都分行","outAcntNo":"687372890237","khxkjPic":"https://dilifu.oss-cn-shenzhen.aliyuncs.com/applyment/ba84f8af-0672-466e-837d-32408002da21.jpg","flagTp":"1","licPic1":"https://dilifu.oss-cn-shenzhen.aliyuncs.com/applyment/9a4fcf53-7e56-48cd-8913-c18a7e61c432.jpg","licNo":"91440101MA5D58TW3G","licTov":"长期","platNameCn":"超市","email":"17316868487@sohu.com","contactPerson":"曾子朝","contactMobile":"17316868487","contractName":"高校商户服务合作","contractUrl":"https://dilifu.oss-cn-shenzhen.aliyuncs.com/applyment/c0aae261-d63e-4c86-b2a9-ecd9e40359e3.jpg","startDate":"2022-07-01","endDate":"2030-07-01"}',
      raw_para: [],
    },
    event: {
      pre_script: "",
      test: "",
    },
    header: {
      parameter: [
        {
          key: "Accept",
          value: "*/*",
          is_checked: 1,
        },
        {
          key: "Accept-Encoding",
          value: "gzip, deflate, br",
          is_checked: 1,
        },
        {
          key: "User-Agent",
          value: "PostmanRuntime-ApipostRuntime/1.1.0",
          is_checked: 1,
        },
        {
          key: "Connection",
          value: "keep-alive",
          is_checked: 1,
        },
      ],
    },
    query: {
      parameter: [],
    },
    cookie: {
      parameter: [],
    },
    resful: {
      parameter: [],
    },
  },
  response: {
    success: {
      raw: "",
      parameter: [],
      expect: {
        name: "成功",
        isDefault: 1,
        code: 200,
        contentType: "json",
        verifyType: "schema",
        mock: "",
        schema: {},
      },
    },
    error: {
      raw: "",
      parameter: [],
      expect: {
        name: "失败",
        isDefault: -1,
        code: 404,
        contentType: "json",
        verifyType: "schema",
        mock: "",
        schema: {},
      },
    },
  },
  is_check_result: 1,
  check_result_expectId: "",
  is_example: -1,
  is_locked: -1,
  enable_ai_expect: -1,
  enable_server_mock: -1,
  ai_expect: {
    none_math_expect_id: "",
    list: [],
  },
  is_changed: -1,
  is_first_match: -1,
};

module.exports = requestData;
